tap "mas-cli/tap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

cask_args appdir: "~/Applications"

brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

brew "coreutils"
brew "findutils"
brew "autoconf"
brew "pkg-config"
brew "mackup"
brew "mas"
brew "n"

brew "wget"
brew "curl"
brew "httpie"
brew "bat", args: ["build-from-source"]
brew "micro"
brew "exa"
brew "fd"
brew "tree"
brew "ncdu"
brew "fzf"
brew "ripgrep"

brew "git"
brew "git-extras"
brew "git-delta"
brew "git-flow"
brew "gist"
brew "gh"

cask "google-chrome"
cask "firefox"
cask "java" unless system "/usr/libexec/java_home --failfast"
cask "ilya-birman-typography-layout"
cask "iterm2"
cask "visual-studio-code"
cask "sublime-text"
cask "numi"
cask "jetbrains-toolbox"
cask "osxfuse"

cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookapk"
cask "quicklookase"
cask "webpquicklook"
cask "suspicious-package"

cask "font-fira-code"
cask "font-fira-mono"
cask "font-powerline-symbols"
cask "font-powerline-symbols"
cask "font-inter"

mas "Xcode", id: 497799835
mas "1Password", id: 443987910
