command_timeout = 2000
format = "$os$username$hostname$directory$custom$git_simple$nodejs$line_break$character"

[custom.git_simple]
command = "starship-git-simple"
style = ""
when = "true"

[directory]
style = "cyan"

[hostname]
format = "[$ssh_symbol$hostname]($style) in "
ssh_symbol = "@"
style = "yellow"

[nodejs]
format = "[[ 󰎙 ($version) ](fg:#5c5c5c)]($style)"

[os]
disabled = true
format = "[$symbol]($style) "
style = "white"

[os.symbols]
Linux = ""
Macos = ""

[username]
format = "[$user]($style) "
style_user = "white dimmed"

[username.aliases]
"yuri.sementsov@usgroup.loc" = "Yuri.Sementsov"
